// История проекта для админки (Задачи → История): всё, что попало в main, и публикации в Telegram-канал.
// Источники: смерженные PR (API GitHub, с описаниями; без токена — git log) и ветки tg/* (очередь постов канала).
// Результат — src/data/history.json; при деплое GitHub Actions пересобирает его, HubDO досоздаёт недостающие записи.
// Запуск: node scripts/build-history.mjs  (в CI: GITHUB_TOKEN и GITHUB_REPOSITORY, полная история git — fetch-depth: 0)
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/data/history.json");
const REPO = process.env.GITHUB_REPOSITORY || "oxionezhkov-hub/helpmedoctor";
const git = (...args) => execFileSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 << 20 }).trim();

// Описание PR без служебных строк (подпись Claude Code, ссылка на сессию), не длиннее 1800 символов
function cleanBody(body) {
  const lines = String(body || "").replace(/\r/g, "").split("\n")
    .filter((l) => !/Generated with \[Claude Code\]|claude\.ai\/code|^_Generated by|^---\s*$|^(Co-authored-by|Co-Authored-By|Claude-Session):/i.test(l));
  const text = lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
  return text.length > 1800 ? `${text.slice(0, 1800).replace(/\s+\S*$/, "")}…` : text;
}

function classify(title, branch = "") {
  if (/^Блог/i.test(title) || branch.startsWith("blog/")) return { type: "content", labels: ["история", "блог"] };
  if (/telegram|канал/i.test(title) || branch.startsWith("tg/")) return { type: "marketing", labels: ["история", "telegram"] };
  if (/исправ|ошибк|баг|fix/i.test(title)) return { type: "bug", labels: ["история"] };
  return { type: "feature", labels: ["история"] };
}

async function fromGithub() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) return null;
  const out = [];
  for (let page = 1; page <= 20; page++) {
    const r = await fetch(`https://api.github.com/repos/${REPO}/pulls?state=closed&base=main&per_page=100&page=${page}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "User-Agent": "helpmedoctor-history" },
    });
    if (!r.ok) throw new Error(`GitHub API ${r.status}`);
    const list = await r.json();
    for (const p of list) {
      if (!p.merged_at) continue;
      const cls = classify(p.title, p.head?.ref || "");
      let descr = cleanBody(p.body);
      // У статей блога — сразу список новых и обновлённых статей со ссылками
      if (cls.type === "content" && p.merge_commit_sha) {
        try { const files = blogFiles(p.merge_commit_sha); if (files) descr = `${files}\n\n${descr}`.trim(); } catch {}
      }
      out.push({ key: `pr:${p.number}`, pr: p.number, date: p.merged_at, title: p.title.trim(), descr, url: p.html_url, ...cls });
    }
    if (list.length < 100) break;
  }
  return out;
}

// Без токена: коммиты main первого уровня — merge-коммиты PR (заголовок во второй строке) и squash-коммиты «… (#N)»
function fromGit() {
  const raw = git("log", "origin/main", "--first-parent", "--format=%H%x1f%cI%x1f%s%x1f%b%x1e");
  const out = [];
  for (const rec of raw.split("\x1e")) {
    const [hash, date, subject = "", body = ""] = rec.trim().split("\x1f");
    if (!hash) continue;
    let pr = null;
    let title = subject.trim();
    const merge = /^Merge pull request #(\d+)/.exec(title);
    const squash = /\(#(\d+)\)\s*$/.exec(title);
    if (merge) {
      pr = Number(merge[1]);
      title = body.split("\n").map((s) => s.trim()).find(Boolean) || title;
    } else if (squash) {
      pr = Number(squash[1]);
      title = title.replace(/\s*\(#\d+\)\s*$/, "");
    }
    if (/^Initial commit$/i.test(title)) continue;
    const key = pr ? `pr:${pr}` : `commit:${hash.slice(0, 10)}`;
    let descr = merge ? "" : cleanBody(body);
    if (!descr && /^Блог/i.test(title)) descr = blogFiles(hash);
    out.push({ key, pr, date, title, descr, url: pr ? `https://github.com/${REPO}/pull/${pr}` : `https://github.com/${REPO}/commit/${hash}`, ...classify(title) });
  }
  return out;
}

// Статьи блога, которые затронул коммит (новые и обновлённые) — по исходникам scripts/site/posts/<slug>.mjs
function blogFiles(hash) {
  const rows = git("show", "--name-status", "--format=", hash).split("\n").filter((l) => /scripts\/site\/posts\/[\w-]+\.mjs$/.test(l));
  return rows.map((l) => {
    const [st, f] = l.split(/\s+/);
    const slug = f.split("/").pop().replace(/\.mjs$/, "");
    let existed = st !== "A";
    try { git("cat-file", "-e", `${hash}^:public/blog/${slug}/index.html`); existed = true; } catch {}
    return `${existed ? "Обновлена" : "Новая статья"}: https://helpmedoctor.ru/blog/${slug}/`;
  }).join("\n");
}

// Ветки tg/* — публикации в канал: заголовок коммита и сводка по постам очереди
function fromTelegram() {
  let refs = "";
  try { refs = git("for-each-ref", "refs/remotes/origin/tg/", "--format=%(refname:short)"); } catch { return []; }
  const out = [];
  for (const ref of refs.split("\n").filter(Boolean)) {
    const branch = ref.replace(/^origin\//, "");
    const [date, subject] = git("log", ref, "-1", "--format=%cI%x1f%s").split("\x1f");
    const files = git("ls-tree", "-r", "--name-only", ref, "content/telegram-channel/queue").split("\n").filter((f) => f.endsWith(`${branch.slice(3)}.json`));
    const kinds = { text: 0, photo: 0, album: 0, document: 0, quiz: 0, edit: 0, delete: 0, channel: 0 };
    let first = "";
    for (const f of files) {
      let steps = [];
      try { steps = JSON.parse(git("show", `${ref}:${f}`)); } catch {}
      for (const s of steps) {
        const k = s.edit ? "edit" : s.delete ? "delete" : s.channel ? "channel" : s.album ? "album" : s.document ? "document" : s.quiz || s.poll ? "quiz" : s.photo ? "photo" : s.text ? "text" : null;
        if (k) kinds[k] += s.delete ? (Array.isArray(s.delete) ? s.delete.length : 1) : 1;
        if (!first && (s.text || s.caption)) first = String(s.text || s.caption).replace(/<[^>]+>/g, "").split("\n").find((l) => l.trim()) || "";
      }
    }
    const names = { text: "текстовых постов", photo: "постов с картинкой", album: "каруселей", document: "PDF", quiz: "опросов", edit: "правок постов", delete: "удалено сообщений", channel: "изменений оформления канала" };
    const summary = Object.entries(kinds).filter(([, n]) => n).map(([k, n]) => `${names[k]}: ${n}`).join(" · ");
    out.push({
      key: `tg:${branch}`, date, title: subject.startsWith("Telegram") ? subject : `Telegram-канал: ${subject}`,
      descr: [summary, first && `Первый пост: «${first.slice(0, 160)}»`].filter(Boolean).join("\n"),
      url: `https://github.com/${REPO}/tree/${branch}`, ...classify("", branch),
    });
  }
  return out;
}

let prs = null;
try { prs = await fromGithub(); } catch (e) { console.warn(`GitHub API недоступен (${e.message}) — беру историю из git`); }
const items = [...(prs || fromGit()), ...fromTelegram()].sort((a, b) => a.date.localeCompare(b.date));
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(items, null, 1)}\n`);
console.log(`✓ ${OUT}: ${items.length} записей (${prs ? "GitHub API" : "git"} + Telegram)`);
